<?php

declare(strict_types=1);

namespace Twent\Framework\Http\Enums;

enum ContentType: string
{
    case AudioAac = 'audio/aac';
    case ApplicationXAbiword = 'application/x-abiword';
    case ApplicationXFreearc = 'application/x-freearc';
    case ImageAvif = 'image/avif';
    case VideoXMsVideo = 'video/x-msvideo';
    case ApplicationVndAmazonEbook = 'application/vnd.amazon.ebook';
    case ApplicationOctetStream = 'application/octet-stream';
    case ImageBmp = 'image/bmp';
    case ApplicationXBzip = 'application/x-bzip';
    case ApplicationXBzip2 = 'application/x-bzip2';
    case ApplicationXCdf = 'application/x-cdf';
    case ApplicationXCsh = 'application/x-csh';
    case TextCss = 'text/css';
    case TextCsv = 'text/csv';
    case ApplicationMsWord = 'application/msword';
    case ApplicationVndOfficeDocumentWordProcessingMLDocument = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';
    case ApplicationVndMsFontObject = 'application/vnd.ms-fontobject';
    case ApplicationEpubZip = 'application/epub+zip';
    case ApplicationGzip = 'application/gzip';
    case ImageGif = 'image/gif';
    case TextHtml = 'text/html';
    case ImageVndMicrosoftIcon = 'image/vnd.microsoft.icon';
    case TextCalendar = 'text/calendar';
    case ApplicationJavaArchive = 'application/java-archive';
    case ImageJpeg = 'image/jpeg';
    case TextJavascript = 'text/javascript';
    case ApplicationJson = 'application/json';
    case ApplicationLdJson = 'application/ld+json';
    case AudioMidi = 'audio/midi';
    case AudioMpeg = 'audio/mpeg';
    case VideoMp4 = 'video/mp4';
    case VideoMpeg = 'video/mpeg';
    case ApplicationVndAppleInstallerXml = 'application/vnd.apple.installer+xml';
    case ApplicationVndOasisOpenDocumentPresentation = 'application/vnd.oasis.opendocument.presentation';
    case ApplicationVndOasisOpenDocumentSpreadsheet = 'application/vnd.oasis.opendocument.spreadsheet';
    case ApplicationVndOasisOpenDocumentText = 'application/vnd.oasis.opendocument.text';
    case AudioOgg = 'audio/ogg';
    case VideoOgg = 'video/ogg';
    case ApplicationOgg = 'application/ogg';
    case AudioOpus = 'audio/opus';
    case FontOtf = 'font/otf';
    case ImagePng = 'image/png';
    case ApplicationPdf = 'application/pdf';
    case ApplicationXHttpdPhp = 'application/x-httpd-php';
    case ApplicationVndMsPowerpoint = 'application/vnd.ms-powerpoint';
    case ApplicationVndOfficeDocumentPresentation = 'application/vnd.openxmlformats-officedocument.presentationml.presentation';
    case ApplicationVndRar = 'application/vnd.rar';
    case ApplicationRtf = 'application/rtf';
    case ApplicationXSh = 'application/x-sh';
    case ImageSvgXml = 'image/svg+xml';
    case ApplicationXTar = 'application/x-tar';
    case ImageTiff = 'image/tiff';
    case VideoMp2t = 'video/mp2t';
    case FontTtf = 'font/ttf';
    case TextPlain = 'text/plain';
    case ApplicationVndVisio = 'application/vnd.visio';
    case AudioWav = 'audio/wav';
    case AudioWebm = 'audio/webm';
    case VideoWebm = 'video/webm';
    case ImageWebp = 'image/webp';
    case FontWoff = 'font/woff';
    case FontWoff2 = 'font/woff2';
    case ApplicationXHtmlXml = 'application/xhtml+xml';
    case ApplicationVndMsExcel = 'application/vnd.ms-excel';
    case ApplicationVndOfficeDocumentSpreadsheetML = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    case ApplicationXML = 'application/xml';
    case ApplicationVndMozillaXulXml = 'application/vnd.mozilla.xul+xml';
    case ApplicationZIP = 'application/zip';
    case Video3gpp = 'video/3gpp';
    case Video3gpp2 = 'video/3gpp2';
    case ApplicationX7zCompressed = 'application/x-7z-compressed';
}
